MCSC-566 Update Deprecated SafeRedirectURL Library
hmrc/calculate-public-pension-adjustment-frontend pull request #130
Opened 2023-11-16 10:51 UTC by bharti5verma

2023-11-20 09:57 UTC, MichaelAAbbott submitted a review, later dismissed

2023-11-23 09:20 UTC, SandipKhedekar requested changes

2023-11-23 09:20 UTC, SandipKhedekar commented on conf/application.conf
> +  allowedRedirects = ["localhost", "www.tax.service.gov.uk"]
Remove **www.tax.service.gov.uk** from **allowedRedirects** list.

2023-11-23 12:12 UTC, bharti5verma commented on conf/application.conf
> +  allowedRedirects = ["localhost", "www.tax.service.gov.uk"]
Done.

2023-11-23 12:37 UTC, SandipKhedekar approved these changes

2023-11-23 12:38 UTC, merged