MCSC-731 Consume API call to check submission
hmrc/calculate-public-pension-adjustment-frontend pull request #193
Opened 2024-03-20 16:08 UTC by mrah93

2024-03-21 12:06 UTC, ElliotAndersonHMRC requested changes

2024-03-21 12:06 UTC, ElliotAndersonHMRC commented on conf/application.conf
> +    optionalAuth = true
Make sure this is false before we merge

2024-03-21 14:38 UTC, mrah93 commented on conf/application.conf
> +    optionalAuth = true
Done

2024-03-27 16:49 UTC, SandipKhedekar approved these changes

2024-03-27 16:53 UTC, merged